name: Docker image

on:
  workflow_dispatch:
    inputs:
      revision:
        description: 'revision'
        required: true
        default: 'main'
        type: string
      useLatestVersion:
        description: 'Use as latest version'
        required: false
        default: false
        type: boolean
jobs:
  BuildImages:
    env:
      IMAGE_NAME: edimarlnx/prometheus-mongodb-adapter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.revision }}"
      - name: Build
        run: docker build -t ${IMAGE_NAME}:${{ inputs.revision }} .
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image
        run: docker push ${IMAGE_NAME}:${{ inputs.revision }}
      - name: Push image as latest
        if: ${{ inputs.useLatestVersion }}
        run: |
          docker tag ${IMAGE_NAME}:${{ inputs.revision }} ${IMAGE_NAME}:latest
          docker push ${IMAGE_NAME}:latest
